name: Bandit
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '41 2 * * 4'

permissions:
  contents: read

jobs:
  bandit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install Bandit
        run: pip install bandit bandit-sarif-formatter
      - name: Run Bandit
        run: bandit -r src/ -ll -f sarif -o results.sarif
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          category: bandit
